/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 animalnew.gltf
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/animalnew.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Sphere005.geometry} material={materials['Material.007']} position={[-0.38, 0.02, 3.27]} rotation={[-3.14, 0.08, 3.09]} scale={0.05} />
      <mesh geometry={nodes.Icosphere002.geometry} material={materials['Material.003']} position={[-0.39, -0.01, -0.61]} scale={1.14} />
      <mesh geometry={nodes.Roundcube.geometry} material={materials['Material.010']} position={[-0.38, 0, -0.62]} scale={0.98} />
      <mesh geometry={nodes.Roundcube001.geometry} material={materials['Material.009']} position={[-0.38, 0.2, -0.55]} scale={0.26} />
      <mesh geometry={nodes.Roundcube000.geometry} material={materials['Material.011']} position={[1.92, -0.21, -0.2]} rotation={[-2.67, 1.48, 2.68]} scale={0.19} />
      <mesh geometry={nodes.Sphere.geometry} material={materials.Material} position={[0.2, -0.13, -0.2]} scale={[1.13, 1.2, 1.2]} />
      <mesh geometry={nodes.BezierCurve002.geometry} material={materials['Material.006']} position={[1.15, -0.37, 2.2]} rotation={[0, 0.76, 0]} scale={0.41} />
      <mesh geometry={nodes.BezierCurve.geometry} material={materials['Material.005']} position={[-0.39, -0.01, -0.61]} scale={1.14} />
      <mesh geometry={nodes.Icosphere.geometry} material={materials['Material.001']} position={[-0.39, -0.01, -0.61]} scale={1.14} />
      <mesh geometry={nodes.Sphere002.geometry} material={materials['Material.008']} position={[-0.38, 0.02, 3.27]} rotation={[-3.14, 0.08, 3.09]} scale={0.05} />
      <mesh geometry={nodes.Sphere001.geometry} material={materials['Material.004']} position={[0.2, 0, -0.29]} scale={[1.19, 1.27, 1.27]} />
      <mesh geometry={nodes.Roundcube002.geometry} material={materials['Material.011']} position={[1.92, -0.21, -0.2]} rotation={[-2.67, 1.48, 2.68]} scale={0.19} />
    </group>
  )
}

useGLTF.preload('/animalnew.gltf')
